### ISSUE TITLE
Newer volume types are not supported

### ISSUE THREAD

**Issue by doriordan** [doriordan/skuber#184]
The full set of volume type currently  supported by Kubernetes is at:
https://kubernetes.io/docs/concepts/storage/volumes/#types-of-volumes

As of Kubernetes 1.11 this includes the following that are not presently supported by skuber:

azureDisk
azureFile
cephfs
csi
fc
flocker
local
projected
portworxVolume
quobyte
scaleIO
storageos
vspehereVolume

If any of these types are specified in a volume spec, skuber will raise an exception when unmarshalling the specification. As new volume types are added very often, skuber ideally needs to support relaxed unmarshalling such that volume types that are not known to it are converted into some generic representation instead of throwing an exception.

**Comment by cgbaker** [comment]
It feels like this could be as simple as `GenericVolumeSource(json: JsValue)`, perhaps with an attempt to pull out the type string (e.g., `scaleIO`), perhaps not.

**Comment by doriordan** [comment]
@cgbaker I agree with the basic idea of `GenericVolumeSource`, although I am not really keen on exposing `JsValue` in the model as I think it feels like a leaky abstraction exposing that the formatters used by Skuber are Play formatters. 
I would prefer a `String` containing the json value which the user (if needed) can then convert into their model using their own Json framework. A bit less efficient but I doubt thats a significant issue as I can't imagine most volume specs are very large..
The other requirement would be that if a Volume spec is read and then written, it should result in no change - we can easily add unit testing for that.

**Comment by cgbaker** [comment]
I don't have any objection to `String`-encoded JSON. I'll add a test to ensure that read/write are inverses.

**Comment by cgbaker** [comment]
I'm starting this work right now.

**Comment by doriordan** [comment]
Closing this as due to #194 - future enhancements can add specific support for additional volume types but the original reported issue is resolved with the addition of generic volume support.

**Comment by cgbaker** [comment]
@doriordan I'm thinking maybe this issue needs to be re-opened.... the parsing of `Volume` should support generic, so that the pod parsing error from #183 should be gone. however, parsing of `PersistentVolume` will still fail on an unsupported volume type, meaning that (e.g.) a listing of all PersistentVolumes in a namespace will fail. I will submit a documenting test and then a fix, which may simply involve changing `GenericVolumeSource` from `extends VolumeSource` to `extends PersistentVolumeSource` and updating the parsers.
